### ISSUE TITLE
Support for Ubuntu 22.04

### ISSUE THREAD

**Issue by ajdecon** [NVIDIA/deepops#1201]
We should add support to DeepOps for Ubuntu 22.04.

Making this work will require that we ensure all the components we install include support for the new version.

## TODO

- [ ] Put together list of components and determine minimum version for support
- [ ] Add 22.04 to CI testing
- [ ] Manual test of 22.04 on physical hardware

## Component list

- [ ] NVIDIA GPU driver
- [ ] NVIDIA CUDA Toolkit
- [ ] Slurm
- [ ] Kubernetes
- [ ] NVIDIA MOFED
- [ ] ...

**Comment by doganulus** [comment]
Is there any update about DeepOps on 22.04?

**Comment by supertetelman** [comment]
I think we can close this issue. All current Slurm and K8s testing is being done on Ubuntu 22.04.
